const Codes = {
  SUCCESS: 200,
  INTERNAL_ERROR: 500,
  UNAUTHORIZED: 401,
  INVALID_TOKEN: -1,
  INVALID_APIKEY: -1,
  RESPONSE_ERROR: 0,
  RESPONSE_SUCCESS: 1,
  MISSING_FIELD: 2,
  NO_DATA_FOUND: 3,
  PHONE_VERIFICATION_PENDING: 4,
  PROFILE_SETUP_PENDING: 5,
};

export default Codes;
